packages/addons/service/multimedia/vdr-addon/package.mk
packages/addons/service/multimedia/vdr-addon/source/bin/vdr.start
packages/addons/service/multimedia/vdr-addon/source/resources/language/English/strings.xml
packages/addons/service/multimedia/vdr-addon/source/resources/settings.xml
packages/addons/service/multimedia/vdr-addon/source/settings-default.xml
packages/multimedia/vdr-plugin-epgfixer/package.mk
packages/multimedia/vdr-plugin-epgfixer/patches/vdr-plugin-epgfixer-01_makefile.patch
tools/mkpkg/mkpkg_vdr-plugin-epgfixer

A very valuable plugin to deal with ugly epg data broadcasted by providers.
An example of that ugly epg:
an EIT event has short_text and description tags and both can be used as an event description.
But for some events only short_text is broadcasted, for some only description or the text is
splitted between them. It mostly depends on EIT table id type - present/following or schedule.
E.g "Champions League. Schalke - Real Madrid." may be shown in KODI for some events as 
"Schalke - Real Madrid." or  "Champions League." for other which is very annoying. This
particular issue can be fixed in a skin (all skins with PVR support) but there will still be
other epg errors - you never know, it depends on your provider. So, to my view, it's better to
give a user an opportunity to correct them with …

add vdr-plugin-epgfixer

---

packages/multimedia/vdr-satip/package.mk

- update to vdr-satip-1.0.0
- this is a major update of the plugin and the first real usable version for every hardware besides the Octopus Net

vdr-satip: update to vdr-satip-1.0.0

---

packages/sysutils/ntfs-3g_ntfsprogs/patches/ntfs-3g_ntfsprogs-01-meh-gcrypt.patch

AM_PATH_LIBGCRYPT is undefined if libgcrypt is not (yet)
built, and we dont depend on gcrypt...

ntfs-3g_ntfsprogs: fix gcrypt check in autoreconf

---

packages/linux/patches/3.17.7/linux-226-geniatech-t230-tuner.patch

This patch adds support for Geniatech T230 USB DVB-T2/T/C tuner [0572:c688] that is also sold as August T210v2 or MyGica T230. It's currently the lowest cost DVB-T2 tuner that's working reliably. The driver is already in media_tree and will be in kernel 3.19. Before that the following changes are needed:
si2168: add support for inverting the TS clock
si2157: add support for the Si2148 tuner (uses same firmware as Si2158)
cxusb: add the device specific functions
em28xx: initialize si2168_config with zeroes before using

linux: add patch for Geniatech T230 USB DVB-T/T2/C tuner

---

packages/tools/bcm2835-bootloader/files/create_sdcard

this is legacy, and probably broken. now we do provide
ready to use images.
this reverts debed63cff2951690191542e6daf04b3afdf0eaa
closes #3761
@sraue @MilhouseVH any objections?

create_sdcard: remove support for creating images

---

packages/tools/u-boot/files/create_sdcard

In some computers mkfs try to creating filesystem, before kernel update partition table.

Add sleep before  creating filesystem

---

packages/graphics/giflib/package.mk

giflib:host required for kodi's I*** new texturepacker
giflib:target may be required later, for kodi

new package: giflib

---

scripts/checkdeps

projects can define EXTRA_DEPS and EXTRA_DEPS_PKG in projects/xxx/options
//cc @codesnake
example:
```
EXTRA_DEPS="mkimage"
EXTRA_DEPS_PKG="u-boot-tools"
```

scripts/checkdeps: allow project specific deps

---

config/noobs/partitions.json
scripts/image

When installing two OpenELEC based distro with NOOBS, the labels of the SYSTEM partitions conflict. This fix address that problem by prefixing the names of these partitions by the DISTRONAME.
If you think there is a better way to fix this bug, tell me how and I will send another PR.

Fix multiple installations in NOOBS

---

packages/mediacenter/kodi/profile.d/00-addons.conf

this was requested by @ksooo
most of the potential issues I can think of are fixed already in bf42102
addons are not allowed to override anything that is already set via system profile.d/ scripts.
however, a rogue addon could "sleep 100000" thus effectively preventing stuff sourcing /etc/profile from starting. but addons can do other bad things as well, anyway. if one does such sh** he should be beaten.
pls dont merge. lets discuss it first and then decide if we want it.

[RFC] allow addons to ship profile.d scripts

---

projects/imx6/bootloader/uEnv.txt
projects/imx6/linux/linux.arm.conf

- This should go to 5.0
- The bump is again needed for usb dual tv tuner card - Evolve Venus
Btw. it's not good to nail such values into the kernel config, cause they are not overwritten properly by user supplied argument.

IMX: Revisit coherent_pool

---

packages/linux-drivers/bcm_sta/patches/bcm_sta-005-CFG80211_BSS_FTYPE_UNKNOWN-linux-3.18.0.patch

Fixes following compile error:
/var/lib/hudson/jobs/OpenELEC/workspace/build.OpenELEC-Generic.x86_64-devel/bcm_sta-6.30.223.248/x86-64/src/wl/sys/wl_cfg80211_hybrid.c:2013:9: error: too few arguments to function 'cfg80211_inform_bss'
cbss = cfg80211_inform_bss(wiphy, channel, (const u8 *)(bi->BSSID.octet),

fix compile for Linux 3.18

---

scripts/unpack

This pull request allows binary patches to be applied during the OpenELEC build process.
As one example, pull request [PR6201](https://github.com/xbmc/xbmc/pull/6201) contains a binary patch (image file, test.png, in commit [8438b740](https://github.com/Montellese/xbmc/commit/8438b740f24cd3085b711c8e85f4204001f67ff9)) that would otherwise not be possible to apply on top of OpenELEC without repackaging kodi..

Enable binary patching

---

projects/RPi/options
projects/WeTek_Play/options
scripts/image
scripts/mkimage

- projects are allowed to set name for target kernel (RPi/WeTek_Play use kernel.img)
- minors
@sraue @MilhouseVH could you confirm this still produces valid images for RPi/x86, just in case ?

mkimage enhancements

---

packages/multimedia/vdr-plugin-restfulapi/package.mk
packages/multimedia/vdr-plugin-restfulapi/patches/vdr-plugin-restfulapi-01_makefile.patch

New upstream version has now Documentation for the wirbelscan extension and feature complete.
At least for now ;)

New upstream version requires change of makefile patch

---

projects/WeTek_Play/patches/linux/100-fix-23hzpixelclock.patch
projects/WeTek_Play/patches/linux/30-g18dtd.patch
projects/WeTek_Play/patches/linux/70-remove-amvideocap-spam.patch
projects/WeTek_Play/patches/linux/80-ge2d-fix-ge2d_state-race.patch
projects/WeTek_Play/patches/linux/90-meson6-maxclock-unclamp.patch
projects/WeTek_Play/patches/linux/95-meson6-fixhdmitx-audiolock-1080p24.patch

Those contain the following fixes for the wetek.play - this is all kernel related:
1.  pixelclock for 23.976Hz mode was wrong
2. yamaha amp (and maybe others) couldn't lock audio in 1080p24 mode (tried it with 44k1, 48k and 96k - none worked before - all work with my patch)
3. allow 1.5ghz for the meson6 cpu (there was still a clamp to 12000 internally)
4. fix race condition in ge2d (which made boblight-aml stuck after some time of usage)
5. add the amvideocap device to the devicetree (needed for boblight-aml).

Wetekfixes

---

packages/linux/patches/3.18.3/linux-999.06-radeon-upstream-fixes.patch

This fixes some performance regressions on Kabini and Aruba. Sadly it does not solve anything when also applied to E-Series.
Should be picked until upstream knows what's going on: https://github.com/OpenELEC/OpenELEC.tv/issues/3763#issuecomment-70944593

Radeon: disable RADEON_GEM_GTT_WC for Kabini and Aruba

---

projects/WeTek_Play/patches/kodi/kodi-8000-backportPR6090.patch

This makes 1080i50 working without a/v sync issues on WetekPlay. Skips are highly reduced also when opening the codec screen.

WT: Backport fullscreen dirty region fixes PR6090

---

packages/linux/patches/3.18.4/linux-227-ds3000-invalid-symbol-rate.patch

When ds3000_set_frontend is called with 0 symbol rate the module would crash with a divide by
zero error.
Added simple symbol rate validation.
Tvheadend was triggering this bug and crashing openelec.

Fix divide by zero crash

---

projects/WeTek_Play/patches/linux/20-wetek_dvb_code.patch

... at least vdr/wirbelscan is confused and thinks there is no dvb-s2 support

wetek_play: avl6211: let userspace knows we support dvbs2

---

packages/sysutils/lirc/scripts/lircd_helper
packages/sysutils/lirc/udev.d/98-lircd.rules

Hi,
This fixes ir blasting and the possibility to use custom .config/lircd.conf for any remote.
This has been broken for a long time but the wiki guides still refers to this method.

lirc: fixed ir blasting

---

packages/mediacenter/kodi/patches/kodi-999.96-PR6356.patch

This fixes: https://github.com/OpenELEC/OpenELEC.tv/commit/9188d497e663dc23bbd6c4b073dae5aee51e23b2
There was an error in the fractional part computation, which took the offset into account

Kodi: Update PR6356 (which was fixed up before the merge)

---

packages/linux/patches/3.19/linux-950-saa716x_PCIe_interface_chipset.patch

(driver support for TechniSat SkyStar 2 eXpress)
based on https://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/commit/?id=a2ea5561173f5c2c14e6050b261d225acd99fa08

linux: Update saa716x PCIe interface chipset patch

---

config/arch.arm

GCC 4.9 added support for armv7ve, use it for cortex-a7 and cortex-a15

GCC 4.9 has support for armv7ve

---

packages/sysutils/eventlircd/udev.d/98-eventlircd.rules

Tweak to support the newer PS3 BD (with IR) remote which identifies differently. 
```
Version 1
[  142.524200] input: BD Remote Control as /devices/platform/bcm2708_usb/usb1/1-1/1-1.3/1-1.3:1.0/bluetooth/hci0/hci0:43/0005:054C:0306.0001/input/i$
[  142.533894] sony 0005:054C:0306.0001: input,hidraw0: BLUETOOTH HID v1.00 Gamepad [BD Remote Control] on 00:00:00:00:00:00
-------------
Version 2
[ 7476.763657] input: Sony Computer Entertainment Inc BD Remote Control as /devices/platform/bcm2708_usb/usb1/1-1/1-1.3/1-1.3.3/1-1.3.3:1.0/bluetooth/hci0/hci0:11/0005:054C:0306.000A/input/input9
[ 7476.764266] sony 0005:054C:0306.000A: input,hidraw4: BLUETOOTH HID v1.10 Gamepad [Sony Computer Entertainment Inc BD Remote Control] on 00:00:00:00:00:00
```

Update 98-eventlircd.rules (PS3 BD remote hardware Version #2)

---

packages/mediacenter/kodi/config/guisettings.xml

OpenELEC is designed as a living room appliance and most user use it as such. This means that most of the users will be using HDMI audio and passthrough.
This allows the passthrough options to be available immediately and avoid people from asking stupid questions about how to enable passthrough audio.

Change the default settings level to "advanced"

---

packages/sysutils/lcdproc/package.mk

Builds sometimes fail trying to cp files that don't yet exist when using more than -j1.

lcdproc: don't build parallel

---

projects/imx6/patches/linux/linux-999-9-fritz-stick-1.patch
projects/imx6/patches/linux/linux-999-9-fritz-stick-2.patch

Sadly, we cannot upgrade our imx kernels, here is a backport of the Fritz WLAN v2 driver. Cherry-picked changes.

IMX: Linux: Backport AVM Fritz 2 Stick support - requested by users

---

projects/imx6/patches/linux/linux-225-ct2-devices.patch
projects/imx6/patches/linux/linux-226-pctv292e-devices.patch

In the previous attempt I made a mess with commit so I started from scratch.
Adds support for ct2 with the patch provided by Olli Salonen and in top of this adds support for PCTV 292e. PCTV is tested in the current version on a cubox-i4pro.

Adds support for ct2 (Olli Salonen) and pctv292e in the project imx6

---

projects/RPi/patches/linux/linux-02-STK1160-addFramescaling.patch
projects/RPi/patches/linux/linux-049-STK1160-addFramescaling.patch
projects/RPi2/patches/linux-049-STK1160-addFramescaling.patch
projects/RPi2/patches/linux/linux-02-STK1160-addFramescaling.patch

This adds support for stk1160 framescaling patch, which we can confirm solves https://github.com/OpenELEC/OpenELEC.tv/issues/3503
Confirmed that this solves for our own issue https://github.com/RasPlex/RasPlex/issues/350
I would suggest adding this as patch in packages/linux, but I have only tested this on RPi1 and RPi2 so that's why I'm only adding the patches to these projects.
FYI I'm also working on an actual package.mk for hyperion, but since it requires Qt libs as dependencies it involves fetching some blobs from raspbian. Happy to contribute this, and OpenELEC.settings addon patches once completed.
@stefansaraev @sraue @fritsch  for review 
cc @tociek

Add stk1160 framescaling patch to RPi and RPi2

---

packages/linux/patches/3.18.8/linux-228-fix-tt-ct2-4400v2.patch

RPi2 was still having no support for TechnoTrend CT2-4400v2 (which was introduced in kernel 3.19). This small patch enables gapped clock for CT2-4400 and CT2-4400v2, so that both of them work properly.

linux: fix TechnoTrend CT2-4400v2 clock for RPi2

---

packages/multimedia/libva/patches/libva-0001-x11-dri2-fix-double-Unlocks-SyncHandle.patch

This reverts upstream commit 0804ff786ae178502d6b73d46aa7d56d763e4788   of libva.
Upstream needs to be informed.

libva: x11: dri2: fix double Unlocks/SyncHandle

---

packages/linux/patches/3.17.8/linux-999.06-i915-use-legacy-turbo-support.patch

This fixes: https://bugs.freedesktop.org/show_bug.cgi?id=88012 and https://github.com/OpenELEC/OpenELEC.tv/issues/3726
I wait until pushing a fix for master - as we can see this way, what upstream decides to push in their stable branches.

linux: Use legacy turbo (fixes BYT full freeze)

---

scripts/uninstall

Just thought I would share this.
It's helpful when building new packages to test different config options (shared, static). It allows easy removal of packages from the toolchain and sysroot.
Basically just scripts/build but opposite. Not sure why this doesn't exist already but maybe I'm just missing something.
```
PROJECT=RPi ARCH=arm ./scripts/uninstall parted
```
```
PROJECT=RPi ARCH=arm ./scripts/uninstall parted:host
```

New script - scripts/uninstall

---

projects/RPi2/options

RPi2 supports vfpv4 and the use of neon-vfpv4 produces a working build
Not sure if one is better then the other

Use neon-vfpv4 fpu on RPi2

---

projects/WeTek_Play/patches/linux/80-update_nand_partition_layout.patch

This should fix boot problems on boxes with many defective blocks in NAND memory.

projects/WeTek_Play: Update NAND partition layout

---

packages/linux/patches/3.19.1/linux-999-i915-use-legacy-turbo.patch

This is the baytrail fix which was already pushed to 5.0 in the 3.19.x version, see: https://bugs.freedesktop.org/show_bug.cgi?id=88012

linux: Use legacy turbo

---

packages/linux/patches/linux-010_tivo_slide_pro.patch

The linux kernel has supported the TiVo Slide remote control for some time, but does not recognize the USB ID of the newer Slide Pro. This patch adds the missing data structures so the newer remote will be recognized by the driver, thereby allowing the TiVo, LiveTV, and Thumbs Up/Down buttons to be mapped with a hwdb file.

linux: enable all buttons on TiVo Slide Pro remote

---

packages/linux/patches/3.19.2/linux-228-technotrend-s2-4600.patch

Add support for TechnoTrend TT-connect S2-4600 USB2.0 DVB-S/S2 receiver. This will likely go into kernel 4.1, so not needed after that...
This needs the DS3103 driver changes from 3.19, so I won't backport this to OE5.0 that has 3.17 and 3.18 kernels...

linux: add patch to support TechnoTrend S2-4600 USB DVB-S2 receiver

---

packages/linux/patches/3.19.2/linux-999.05-eMMC-Don-t-initialize-partitions-on-RPMB-flagged-are.patch

this fixes an issue on some baytrail boxes with integrated emmc, where installer hangs / wont detect the target drive.
on that hardware parted and blkid would hang for minute or two, trying to access /dev/rpmb
tested by me and @fritsch on an "wintel" box.
would be nice if RPi dev can check if this doesnt break something.
//cc @MilhouseVH 
EDIT: @MilhouseVH I dont know if RPi/2 has/needs /dev/rpmb. but if it boots with this patch, all fine.

linux: eMMC: Don't initialize partitions on RPMB flagged areas.

---

projects/imx6/patches/linux/linux-225-ct2-devices.patch

The dvbsky driver was backported from 3.19 kernel to get support for TT CT2-4400 and 4650 as well as DVBSky T330 and T680C devices. However, the same driver contains also driver for the DVBSky S860/S960 device.
For S960 a newer version of the m88ds3103 driver was needed, but that was not backported previously. This patch adds m88ds3103 and also modifies the only other device using that demodulator (the PCTV 461e) to add the new parameters for m88ds3103.

linux-imx6: fix m88ds3103 in the TT CT2 patch (DVBSky S960)

---

packages/linux/patches/3.19.2/linux-061-xpad_steamos.patch

Another attempt at fixing xpad for wireless controllers, this time including the patch from https://github.com/ValveSoftware/steamos_kernel/pull/14 
Just tested it, still panics.
Maybe also needs the patch from http://www.spinics.net/lists/linux-input/msg31446.html

[xpad] update steamos patch with urb reuse fix

---

packages/linux/patches/3.19.2/linux-999-11-EDID-Fix-edid-override-and-no-audio-thx-Jani-Nikula.patch

This should fix a long standing issue when users want to boot with their AVRs disabled or resume from suspend and end without audio. 
It's perhaps worth to integrate a working EDID file into OE for easy usage. Was only verified with kms_helper for now.
Edid (Full HD + All bitstream audio codecs): https://dl.dropboxusercontent.com/u/55728161/edid-samsung-marantz.bin

Intel: Fix EDID overriding (makes audio work)

---

projects/imx6/patches/kodi/kodi-17-fix-frametime-for-active-vsync.patch
projects/imx6/patches/kodi/kodi-18-guilib-only-update-scrollinfo-if-frametime-did-chang.patch

After you pushed the Dirty Region fullscreen rework, these two patches are needed to fix the animation speed regression. Testbuild for IMX users, here: https://dl.dropboxusercontent.com/u/55728161/OpenELEC-imx6.arm-5.0.7-fritschgui.tar
Would be nice if some imx users could test that, it should also help a lot on wetek boxes.

IMX: fix menu animation speed regression

---

packages/mediacenter/kodi-binary-addons/audiodecoder.2sf/package.mk
tools/mkpkg/mkpkg_audiodecoder.2sf

This adds a 2sf audio decoder addon.
I consider this a training run, I got another 10 or so on the way, but want to see if this is okay.
I have built it for x86_64 (Generic) and arm (RPi2).

add 2sf audio decoder addon

---

packages/audio/fluidsynth/package.mk
packages/audio/fluidsynth/patches/fluidsynth-01-fix-libdir.patch
packages/audio/libopenmpt/package.mk
packages/mediacenter/kodi-binary-addons/audiodecoder.asap/package.mk
packages/mediacenter/kodi-binary-addons/audiodecoder.dumb/package.mk
packages/mediacenter/kodi-binary-addons/audiodecoder.fluidsynth/package.mk
packages/mediacenter/kodi-binary-addons/audiodecoder.gme/package.mk
packages/mediacenter/kodi-binary-addons/audiodecoder.gsf/package.mk
packages/mediacenter/kodi-binary-addons/audiodecoder.ncsf/package.mk
packages/mediacenter/kodi-binary-addons/audiodecoder.openmpt/package.mk
packages/mediacenter/kodi-binary-addons/audiodecoder.organya/package.mk
packages/mediacenter/kodi-binary-addons/audiodecoder.qsf/package.mk
packages/mediacenter/kodi-binary-addons/audiodecoder.ssf/package.mk
packages/mediacenter/kodi-binary-addons/audiodecoder.upse/package.mk
packages/mediacenter/kodi-binary-addons/audiodecoder.usf/package.mk
packages/mediacenter/kodi-binary-addons/audiodecoder.wsr/package.mk
tools/mkpkg/mkpkg_audiodecoder.asap
tools/mkpkg/mkpkg_audiodecoder.dumb
tools/mkpkg/mkpkg_audiodecoder.fluidsynth
tools/mkpkg/mkpkg_audiodecoder.gme
tools/mkpkg/mkpkg_audiodecoder.gsf
tools/mkpkg/mkpkg_audiodecoder.ncsf
tools/mkpkg/mkpkg_audiodecoder.openmpt
tools/mkpkg/mkpkg_audiodecoder.organya
tools/mkpkg/mkpkg_audiodecoder.qsf
tools/mkpkg/mkpkg_audiodecoder.ssf
tools/mkpkg/mkpkg_audiodecoder.upse
tools/mkpkg/mkpkg_audiodecoder.usf
tools/mkpkg/mkpkg_audiodecoder.wsr

This adds
- a sap audio decoder
- a gme audio decoder
- a gsf audio decoder
- a ncsf audio decoder
- an organya audio decoder
- a qsf audio decoder
- a ssf audio decoder
- a wsr audio decoder
- an upse audio decoder
- a fluidsynth audio decoder (+ lib as static)
- a libopenmpt audio decoder (+ lib as static)
- a dumb audio decoder
- an usf audio decoder

Add audiodecoders

---

packages/mediacenter/kodi/config/appliance.xml

this was reported to cause stuttering/artifacts
note. this only disables tte pvr-specific "signal quality" part of codecinfo screen (g). user can re-enable it if he wants, we just set it default off
@sraue objections ?

kodi: disable pvrplayback.signalquality on new installs

---

packages/mediacenter/kodi/patches/kodi-100.13-udevprovider-filter-out-OE-specific-mounts.patch

this hides /flash and /storage from videos/music -> files -> add -> browse.
@ksooo FYI

kodi/udevprovider: filter out OE specific mounts

---

packages/graphics/bcm2835-driver/package.mk

Safe to include now, before next bcm2835-* bump.

Include libvcsm.so in RPi/RPi2 builds - needed by upcoming firmware

---

packages/network/libnfs/package.mk

libnfs 1.9.7 has been tested in my RPi/RPi2/Generic builds since Feb 10 without any problems.

libnfs: update to 1.9.7

---

packages/linux/patches/4.0.1/linux-228-technotrend-s2-4600.patch

Previously the TT S2-4600 driver worked fine only in some applications (such as tvheadend), but not in others (such as vdr). This patch fixes that by adding a call to su3000_streaming_ctrl after the demod has locked.

linux: TechnoTrend S2-4600 patch improvements

---

packages/multimedia/libva-intel-driver/patches/libva-intel-driver-03-enable-field-rate-mcdi-madi.patch

follow up of: https://github.com/OpenELEC/OpenELEC.tv/pull/4134

libva-intel-driver: pick field_rate workaround for mcdi and madi on Gen6

---

packages/security/libressl/package.mk

cacert.pem was named incorrectly which leads to curl errors with https
```
curl: (77) error setting certificate verify locations:
CAfile: /etc/ssl/cacert.pem
CApath: none
```
This fixes #4137
EDIT: not sure but I think the symlink can be dropped completely. Will update if it isn't needed.

[libressl] fix certificate name

---

packages/mediacenter/kodi-binary-addons/audiodecoder.ncsf/package.mk
packages/mediacenter/kodi-binary-addons/audiodecoder.organya/package.mk
packages/mediacenter/kodi-binary-addons/audiodecoder.qsf/package.mk

due to split of kodiplatform.
don't merge before you have added the platform lib.

bump audiodecoder add-ons

---

packages/devel/enca/package.mk
packages/devel/fribidi/package.mk
packages/sysutils/squashfs/package.mk
packages/tools/hdparm/package.mk
packages/tools/nano/package.mk
packages/x11/util/xorg-launch-helper/package.mk

its not good to export *FLAGS/LIBS globaly. those should be in pre_configure_target() (or whatever makes sense, depending on the package)
some -fwhole-program ldflags removed, not needed.
@sraue

cosmetics ;)

---

projects/imx6/patches/kodi/kodi-27-check-all-resolutions-fixup.patch
projects/imx6/patches/kodi/kodi-28-resolutions-lie-a-bit.patch
projects/imx6/patches/kodi/kodi-29-fixup-render-capture.patch
projects/imx6/patches/kodi/kodi-30-fixup-artifacts-patch-in-a-more-sane-way.patch
projects/imx6/patches/kodi/kodi-31-enumerate-d-modes.patch

- Fixup for EDID
- Fixup for Artifacts
- Enumerate D modes for DVI monitors
- Fix RenderCapture
All those patches (besides the D modes) can be dropped when we reach v15

IMX: Backport latest fixes

---

packages/linux/package.mk

now cuboxi image should be the same as before

linux: for imx6 include soc fan and status led packages

---

packages/devel/libcec/package.mk

Enables building the libcec Python wrapper included in libcec 3.0, in addition to the other wrappers.
It would handy to be able to control libcec from Python.
In my case I've got two cec adapters in my RPi, one to control Kodi, one to control a set-top box through a Python script running on the RPi.

libcec: build python wrapper

---

tools/mkpkg/mkpkg_kodi

I just noticed that the reported git revision in kodi.log and system information looked oddly unfamiliar. Instead of the expected daedd5f on a current master build I saw 42fb669 - the gitrev of the pvr.wmc addon.
I think GIT_REV in mkpkg_kodi should actually be GIT_HASH so that copy_sources creates the VERSION file with the correct info.

mkpkg: fix VERSION information for kodi

---

projects/WeTek_Play/patches/kodi/0017-enable-IEC958.patch

This patch makes my stereo-only USB sound card *not* look like a S/PDIF device.
After this patch DD and DTS passthrough still work fine.

WeTek_Play: Make ugly IEC958 workaround less ulgy

---

projects/WeTek_Play/initramfs/platform_init

This patch sets initial screen resolution to the one reported by u-boot. It allows to get rid of ugly resolution switching on 1920x1080 TVs (which most people use) and provides a better resolution on first boot.

[WeTek_Play] Init framebuffer according to HDMI resolution from kernel command line

---

projects/RPi/initramfs/platform_init
projects/RPi2/initramfs/platform_init

The following settings are (or are about to become) the default on other distributions (Raspbian, OSMC etc.) and it is recommended they should also be the default for OpenELEC too:
```
echo 1 > /sys/devices/system/cpu/cpufreq/ondemand/io_is_busy
echo ondemand > /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor
echo 50 > /sys/devices/system/cpu/cpufreq/ondemand/up_threshold
echo 100000 > /sys/devices/system/cpu/cpufreq/ondemand/sampling_rate
echo 50 > /sys/devices/system/cpu/cpufreq/ondemand/sampling_down_factor
```
The existing values are:
```
rpi22:~ # cat /sys/devices/system/cpu/cpufreq/ondemand/io_is_busy
0
rpi22:~ # cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor
ondemand
rpi22:~ # cat /sys/devices/system/cpu/cpufreq/ondemand/up_threshold
50
rpi22:~ # cat …
```

Configure RPi/RPi2 platform with optimal CPU and IO settings

---

packages/tools/installer/scripts/installer

remove unused menu item, which breaks view log function
create empty log file, so view log function works prior to install

installer: fix menu display, log file function

---

packages/linux/patches/4.1/linux-228-fix-tt-s2-4600.patch

The TT S2-4600 USB receiver is broken in kernel 4.1 (fixed in 4.2) and will
not tune correctly when certain applications (such as vdr) are being used.
This patch backports the fix from 4.2 to 4.1 and can be removed when kernel
4.1 is no longer used.

linux: fix TechnoTrend S2-4600 DVB-S receiver

---

packages/linux/patches/4.1/linux-229-hauppauge-hvr-2205-and-2255.patch

This patch adds support for the Hauppauge HVR-2205/2255 PCIe dual tuners.
These are backported from kernel 4.2, so the patch is unnecessary after
we move on from kernel 4.1.
Note! At the moment this is just compile-tested - don't have access to the tuners at the moment. I have a test build available, if someone wants to test this...

linux: add patch for Hauppauge HVR-2205/2215/2255 support

---

packages/tools/plymouth-lite/patches/plymouth-lite-0.6.0-21-16bpp.patch

See https://github.com/OpenELEC/OpenELEC.tv/pull/4221#issuecomment-117840719
Thanks @popcornmix, @samnazarko

Fix 16bpp plymouth-lite patch which doesn't use stride consistently

---

packages/devel/libcec/patches/libcec-01-add-repeating-keypress.patch
packages/mediacenter/kodi/patches/kodi-200.01-add-settings-for-libcec-button-repeats.patch
packages/mediacenter/kodi/patches/kodi-200.02-dont-discard-libcec-buttons-when-repeat-enabled.patch

This has been in RPi test builds for several months now, and works well.
This PR should be fine for master, but would also be worth having in openelec-6.0 (if you need a backport, let me know).
There's an upstream PR https://github.com/Pulse-Eight/libcec/pull/111 with more details, but this won't be merged until after Isengard, hence this PR which can be dropped once upstream is merged.

[libcec] Add repeating key support from popcornmix repo

---

packages/linux/patches/4.1.3/linux-229-hauppauge-hvr-2205-and-2255.patch

I2C function modifications were missing from the original HVR-2205 patch.
Reported by user Hoffy in the forums:
http://openelec.tv/forum/82-dvb-t-t2-support/77386-hauppauge-hvr-2205-support#144375

linux: add missing I2C functions to the Hauppauge HVR-2205 patch

---

packages/linux/patches/4.1.3/linux-229-hauppauge-hvr-2205-and-2255.patch

Fix the i2c reglen in the HVR-2205 patch. This is now confirmed and working. Sorry for the noise... 
User Hoffy in the forum reported and retested this:
http://openelec.tv/forum/82-dvb-t-t2-support/77386-hauppauge-hvr-2205-support?start=15

linux: fix i2c_reglen in HVR-2205 patch

---

scripts/image

this seems to be leftover from pre-y2k days

scripts/image: do not symlink /usr/var

---

packages/linux/patches/4.1.3/linux-063-xpad-fix_xbox360_wireless.patch

source from Pavel Rojtberg / https://github.com/paroj/xpad
- fixed blinking LED on Xbox 360 Wireless Controllers
- only expose actually connected Xbox 360 Wireless Controllers
- fixed kernel warnings due to submitting active URB requests
- updated Xbox One controller force feedback
- controller still works after suspend/ resume
- Xbox 360 Wireless button mappings are now compatible with Xbox 360 (non-wireless) mappings

linux/drivers/.../xpad: fix operation for xbox 360/one controllers

---

packages/devel/cmake/package.mk

no idea how important this is. docs say "optional, not used much" but @wsnipex said it's good practice to set it. 
ping @sraue

cmake: set CMAKE_SYSTEM_PROCESSOR in toolchain file

---

packages/linux-firmware/brcmfmac_sdio-firmware/system.d/brcmfmac_sdio-firmware-aml@.service
packages/linux-firmware/brcmfmac_sdio-firmware/system.d/brcmfmac_sdio-firmware-imx@.service

should be simple, not oneshot.
because:
meh:~ # systemd-analyze
Bootup is not yet finished. Please try again later.

brcmfmac_sdio-firmware: fix service type

---

packages/network/openssh/package.mk

Enable root password login and ssh-dss public key.
Courtesy of @stefansaraev on #irc.

Fix openssh-7.0p1 package after 24e80bbc - fixes #4280

---

scripts/build
scripts/checkdeps
scripts/skip_unpack
scripts/unpack

instead of comparing "timestamps" (package.mk newer than $STAMP and so on), this aims to detect changes by comparing md5 sums of the whole package dir (via md5deep)
this is good for people who need to do huge rebases often (or switching branches back and forth without actualy building).

buildsys improvements

---

packages/mediacenter/kodi/scripts/kodi.sh

Creating a new crashlog sometimes takes a while, and requesting users to "upload the latest crashlog" has resulted in partial crashlogs being presented (ie. the crashlog is being created as they're uploading it).
Using a temporary filename until the crashlog is complete would help alleviate this problem.

Use a temporary filename when creating new crashlog

---

packages/devel/pkg-config/patches/pkg-config-01_rebuild.patch

because joe the builder dont want to "make clean" even when he is supposed to. 
however. it's a bug.

pkg-config: allow pkg-config:host to be rebuilt

---

packages/tools/bcm2835-bootloader/files/3rdparty/bootloader/config.txt

From the official RPi config tool: https://github.com/asb/raspi-config/commit/4ee1fde44ee544a7eade9ecf94141eb40aabab60
A small fix for turbo to match the config tool and an additional RPi2 preset.
Several tutorials only talk about 1000-500-500, but it actually needs the over_voltage in this config to be stable. So I think it's good to have it mentioned in the default config comments.

Include RPi 2 overlock mode preset

---

packages/linux/patches/4.1.6/linux-230-elgato-eyetv-sat-v3.patch

This adds support for Elgato EyeTV Sat v3 or maybe 2.x (revision is a bit unclear).
It is the same hardware (as already supported v1, v2) with a different hw id.
ping @trsqr if this is a valid fix [(fix is working of course)](http://openelec.tv/forum/83-dvb-s-s2-support/78070-elgato-eyetv-sat#147269)

linux: add Elgato EyeTV Sat v3 (maybe v2.x)

---

packages/virtual/x11/package.mk
packages/wayland/libinput/package.mk

I'd like to still use libinput for testing on my builds (others may too) so adding LIBINPUT="yes" to you local options file will build xf86-input-libinput instead of xf86-input-evdev.
Also bumping libinput to version 1.0.1

Allow building with xf86-input-libinput when specified

---

packages/graphics/giflib/package.mk

used only for texturepacker (host). safe to bump

(jarvis) giflib: update to giflib-5.1.1

---

packages/virtual/x11/package.mk

See discussion in #4324 - thanks @stefansaraev.

Fix error in #4324 that always meant libinput is built

---

packages/lang/gcc/package.mk
packages/linux/patches/4.1.10/linux-004-fix-build-with-gcc-5.patch
packages/sysutils/systemd/package.mk
projects/WeTek_Play/patches/linux/004-fix-build-with-gcc-5.patch
projects/imx6/patches/linux/linux-004-fix-build-with-gcc-5.patch

This PR updates gcc to version 5.2.0 and fixes a few build issues.
The configure switch ```--with-default-libstdcxx-abi=gcc4-compatible``` was taken from arch linux's build
See: https://projects.archlinux.org/svntogit/packages.git/tree/gcc/trunk/PKGBUILD#n81
systemd fails to run with specific compiler optimizations, turning off these optimizations in CFLAGS fixes this.
See: https://bugzilla.yoctoproject.org/show_bug.cgi?id=8291
arm kernel fails to boot with specific compiler optimizations, turning off these optimizations fixes this. This fix is included as three seperate patches for three different kernel versions (imx6, amlogic, and mainline).
See: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=65932
I have only tested this with the RPi2 build (as that is all I have), I would appreciate if …

[gcc] update to 5.2.0

---

packages/linux/patches/4.1.10/linux-200-rtl28xxu-fix-control-message-flaws.patch

@sraue please pick for openelec-6.0
This fixes and closes #4364

[linux] add patch from upstream to fix rtl28xxu

---

distributions/OpenELEC/options
packages/sysutils/lcdproc/package.mk
packages/sysutils/serdisplib/package.mk
packages/sysutils/serdisplib/patches/serdisplib-disable_SDL_crosscompile.patch

Hi,
this request adds support for displays driven by serdisplib through the lcdproc driver glcd.
Header files from serdisplib must be available when glcd is build, else glcd is build without support for serdisplib. 
extend packages/sysutils/lcdproc/package.mk 
If in the file "distributions/OpenELEC/options" SERDISPLIB_SUPPORT is set to "yes", then serdisplib will be a dependency of lcdproc. Furthermore it checks, if the driver glcd is set in LCD_DRIVER, else it will add them automatic to LCD_DRIVER. So an installed serdisplib is nothing without glcd.
add packages/sysutils/serdisplib/package.mk
adds support for serdisplib-1.97.9
Even if SDL is disabled, you must apply the patch "serdisplib-disable_SDL_crosscompile.patch", else configure will fail.

add new package: packages/sysutils/serdisplib 1.97.9

---

scripts/checkdeps
scripts/image

+ Fix the dependencies of OpenElec on a gentoo system in `scripts/checkdeps`
On Gentoo the header-files are always installed with the builded libs/exe, there are no dev- or header-packages available, so fix the `files_pkg`.
Also, build gcc with support for c++, if g++ is not available and use virtual/jre for java (the user can install which jre/jdk he/she like).
`g++  ->   gcc[cxx]`
`jre  ->   virtual/jre`
+ Remove spaces in `scripts/image`.

scripts/checkdeps: fix gentoo deps 

---

scripts/build
scripts/checkdeps
scripts/skip_unpack
scripts/unpack

this is a fix for #4390
buntu 15.04+ is packaging md5deep differently, and the tool is not available anymore

buildsys: do poor man's md5deep

---

packages/sysutils/dosfstools/package.mk
scripts/image

Build dosfstools for the host from `scripts/image` by default, like it is done for squashfs.
Tested the build `dosfstools:host` with a clean build* dir, except toolchain nothing else is needed.
The error i had descriped here #4375 is gone.

Build mkfs.(v)fat from dosfstools for the host

---

packages/mediacenter/kodi/patches/kodi-999.41-KEY_CONFIG.patch

fixes #4401 
should be picked for openelec-6.0 if there is time

kodi: add patch to support keys on the rii mini i8+

---

packages/devel/make/package.mk

I have tested this change. Works without any problems. Recent 4.1 is a minor bugfix release of version 4 we already use. Its released in 2014 and used in most of the recent linux OS.

[make] update to 4.1, update licence, update to secure links

---

packages/audio/pulseaudio/config/pulseaudio-system.conf
packages/audio/pulseaudio/config/system.pa
packages/audio/pulseaudio/package.mk
packages/audio/pulseaudio/profile.d/04-pulseaudio.conf
packages/audio/pulseaudio/system.d/pulseaudio.service
packages/devel/libtool/package.mk
packages/devel/libtool/patches/libtool-03-remove-help2man-dependency.patch
packages/mediacenter/kodi/patches/kodi-100.14-dont-enumerate-pulse-devices.patch

libtool needs this patch on my build machine as there is no /bin/true in the built toolchain for target
(pulseaudio requires libtool:target)

various pulseaudio fixes

---

packages/mediacenter/kodi/config/appliance.xml

Please also pick to 6.0 as pointed out by @anaconda

kodi: disable pvermanager.syncchannelgroups (fixup)

---

packages/wayland/libinput/package.mk
packages/x11/driver/xf86-input-libinput/package.mk

libinput bump is needed by xf86-input-libinput version 0.15.0
and fix xf86-input-libinput default config location

libinput bump to 1.1.0

---

distributions/OpenELEC/options
packages/linux-drivers/RTL8192EU/package.mk
tools/mkpkg/mkpkg_RTL8192EU

This includes D-Link Wireless N300 Nano USB Adapter DWA-131 (Rev E1; USB ID: 2001:3319).
To be 100% honest now, most of this is cargo culted on my part. I copied the package for RTL8192**D**U and worked from that one. I found a new repo that hosted the source code for this chipset's driver and updated everything I could find.
I can't try this out currently as it tries to download the source code from `http://sources.openelec.tv/mirror/RTL8192EU/RTL8192EU-9e65859.tar.xz` and that URL obviously does not exist. Can I get it to compile from a local copy of the repo so I can verify this is working first?
Any suggestions on how to proceeed?
**TODO:**
---
Might I just say, your build pipeline is amazing. Great job! It's welcoming, easy and has great output. Everything's top-notch. I can see you …

Add drivers for RTL8192EU

---

packages/devel/libcec/package.mk
packages/devel/libcec/patches/libcec-02-fix-crash-on-some-systems.patch

Patch made from upstream commit PulseEight/libcec@678739a0d8aa5897fa1906a8fdeeb67b83f7d1e9
This fixes #4412 
This should probably get picked for openelec-6.0 also

libcec: update to version 3.0.1

---

projects/Nvidia_Legacy/linux/linux.x86_64.conf

There is no reason to have different kernel configs for the two projects. Just keep them the same so it's easier to keep track of changes.

Nvidia_Legacy/linux: sync kernel config with Generic

---

packages/audio/taglib/patches/taglib-01_bytevector.patch

cosmetics. the patch is upstream. I have no idea why I thought it's from kodi unified depends (or it got lost in some xbmc pr rebase, dunno)

taglib: update bytevector.patch

---

packages/mediacenter/kodi-binary-addons/pvr.hdhomerun/package.mk
packages/multimedia/libhdhomerun/package.mk

Both commits are needed to successfully build [`pvr.hdhomerun`](https://github.com/kodi-pvr/pvr.hdhomerun).
Creating the pkconfig file in `libhdhomerun` is a rather ugly hack, due to `libhdhomerun` not having a usable `make install` and not installing itself as a library, as it should.
Hopefully Silicon Dust can update their package in future to avoid hacks like this.

Add pvr hdhomerun

---

packages/sysutils/systemd/patches/systemd-06_stop-execute_preset-doing-stupid-things.patch

Need to nop `execute_preset()` in 228 and not `unit_file_preset_all()` to stop systemd populating `/storage/.config/system.d` with useless symlinks.

[systemd] Update our patch to work with systemd-228 - closes #4470

---

packages/graphics/bcm2835-driver/package.mk
packages/tools/bcm2835-bootloader/package.mk

This includes the updated firmware for the RPi zero

bcm2835-driver: update to version 6b7cebd

---

packages/multimedia/ffmpeg/package.mk

Following on from #4488, this will be required by https://github.com/xbmc/xbmc/pull/8583 to enable `png` encoding. No harm in enabling now.

ffmpeg: enable png encoder

---

packages/mediacenter/kodi-binary-addons/audiodecoder.usf/package.mk

package build fails on RPi without this (and is currently missing from 6.0 repo) as first gen. pi doesn't support neon fpu. - this has been "build" tested, I've no idea how to test the actual decoder

audiodecoder.usf: don't build on RPi

---

packages/audio/alsa-plugins/package.mk
packages/audio/pulseaudio/config/system.pa
packages/audio/pulseaudio/package.mk
packages/audio/pulseaudio/profile.d/99-pulseaudio.conf
packages/audio/pulseaudio/system.d/pulseaudio.service
packages/mediacenter/kodi/package.mk

This replaces #4427 
This creates a pulseaudio --> alsa bridge device that shows up in kodi as "PulseAudio Sound Server"
This device can be selected to use pulseaudio output. If not needed then one could select the default sound device that they desire.
I am not 100% sure if the causes audio handling issues and needs to be tested to make sure DTS-HD and TrueHD work on devices that support it.
This was the method as described by @fritsch 
@MilhouseVH can you include this into your test builds?
I tested on the RPi2 and I can still select a passthrough device, so let me know if that bug exists again with this PR.

pulseaudio: use pulseaudio --> alsa bridge

---

scripts/mkimage

I realise the default partition size is large enough for regular releases, however it's not large enough if a user wishes to assist with testing and tries to use a debug-enabled build which is then too large to install. Or if a user has a problem with a stock release, and needs to use a debug enabled build to provide more detailed information.
The size of debug-enabled `SYSTEM`+`KERNEL` is 278MB+10MB (RPi/RPi2) and 347MB+12MB (Generic, including NVidia legacy drivers).
Therefore a partition size of 512MB is comfortably large enough for the foreseeable future, allowing more users to get involved with testing/debugging, and without taking too much extra space from `Storage`.
Given the size of storage devices that most users have available these days, using a partition size that is only just …

[RFC] Stop being stingy with System partition size

---

packages/audio/pulseaudio/config/system.pa

This change makes it safe to enable pulseaudio for all builds
With this change pulseaudio will only be used for bluetooth audio and sending network audio.
It is not practical to configure pulseaudio for HDMI as there are many different options (profile, codecs, default sink, etc)

pulseaudio: remove automatic loading of udev module

---

packages/addons/repository/repository.unofficial.addon.pro/sources/addon.xml
packages/mediacenter/kodi/config/repository.openelec.tv/addon.xml

These are the same cosmetic/description changes that I made to the 7.0 branch yesterday. We also need to lock the unofficial repo to 6.0 addons to avoid it picking up earlier 4.3 ones.

addons: update repo descriptions and lock unofficial to 6.0

---

packages/mediacenter/kodi-binary-addons/audiodecoder.usf/package.mk

applying the same change to 6.0 that we did for 7.0

addons: don't build audiodecoder.usf on RPi

---

packages/mediacenter/kodi-binary-addons/pvr.dvblink/package.mk
packages/mediacenter/kodi-binary-addons/pvr.mythtv/package.mk
packages/mediacenter/kodi-binary-addons/pvr.nextpvr/package.mk
packages/mediacenter/kodi-platform/patches/kodi-platform-02_no-multi-lib.patch
packages/mediacenter/kodi/patches/kodi-100.14-pvr-githashes-20151226.patch

Kodi sources contain outdated addon hashes (not updated since 15.2 final) so mkpkg scripts used to package kodi-binary-addon sources don't give latest packages. If applied to downloaded Kodi sources this patch updates hashes to current. It's not required to build Kodi - but we have to stash a reminder somewhere.

addons: bump pvr.dvblink pvr.mythtv pvr.nextpvr - add kodi patch

---

packages/network/iptables/package.mk

A clean build of OpenELEC will sometimes fail as follows:
```
mv -f .deps/xtables_compat_multi-xtables-standalone.Tpo .deps/xtables_compat_multi-xtables-standalone.Po
/home/neil/projects/OpenELEC.tv/build.OpenELEC-RPi2.arm-7.0-devel/toolchain/bin/armv7ve-openelec-linux-gnueabi-gcc -DHAVE_CONFIG_H -I. -I/home/neil/projects/OpenELEC.tv/build.OpenELEC-RPi2.arm-7.0-devel/iptables-1.6.0/iptables -I..  -D_LARGEFILE_SOURCE=1 -D_LARGE_FILES -D_FILE_OFFSET_BITS=64 -D_REENTRANT      -DXTABLES_LIBDIR=\"/usr/lib/xtables\" -DXTABLES_INTERNAL -I../include -I.. -I/home/neil/projects/OpenELEC.tv/build.OpenELEC-RPi2.arm-7.0-devel/iptables-1.6.0/include -I/home/neil/projects/OpenELEC.tv/build.OpenELEC-RPi2.arm-7.0-devel/iptables-1.6.0 -I/home/neil/projects/OpenELEC.tv/build.OpenELEC-RPi2.arm-7.0-devel/linux …
```

iptables: Fix build failure due to race

---

packages/x11/xserver/xorg-server/system.d/xorg.service

Xorg logs this error on startup:
```_XSERVTransTransNoListen: unable to find transport: tcp
Failed to disable listen for tcp transport[4264579.516]```
The error is harmless to normal operations but this change prevents it. I've been using the same patch in my ATV builds for a while.

xorg: prevent _XSERVTransTransNoListen error

---

scripts/get

This might be a little contentious, but it's a problem I see quite often as I run parallel/concurrent builds.
The change in this PR will block any build that is trying to download a package that is already in the process of being downloaded by another build.
Without this PR, partial (ie. corrupted) downloads are likely when building in parallel.

[get]: Avoid concurrent downloads of the same package

---

projects/imx6/patches/linux/linux-002-rename-sgtl5000-codec.patch

In device tree there is
> model = "On-board Codec";
and this doesn't match any alsa config. That's why it is renamed to
> model = "imx-sgtl5000";
for which we already have imx-sgtl5000.conf file.
This enables to use analog sound output on Hummingboard.

projects/imx6/linux: rename Hummingboard on-board analog sgtl5000 audio codec

---

packages/audio/fluidsynth/package.mk

This disables libsndfile and pulseaudio support as they get automatically picked up.

fluidsynth: disable sndfile and pulseaudio support

---

config/functions
scripts/image

builds created by users in our ecosystem/community should be labelled as such .. it's a friendlier way of saying they are not official builds

cosmetics: rename 'unofficial' to 'community' builds

---

distributions/OpenELEC/options

I discovered some ssh clients collapse whitespace in the banner so the recent change looks like:
##############################################
##############################################```
so this adds whitespace padding to make it look like:
##############################################
##############################################```
not _as_ simple, but still cleaner than the original

banner: fix whitespace padding

---

packages/linux/patches/4.4/linux-228-support-tt-ct2-4650-v2.patch

This patch is probably going into kernel 4.6, so this OE patch
is obsolete after that.

linux: add support for TechnoTrend CT2-4650 version 2

---

packages/linux/patches/4.1.15/linux-231-support-tt-ct2-4650-v2.patch

The same PR for OpenELEC 6.0 branch as well. Due to updates between 4.1 and 4.4 kernels there's a slight change in the patch...

linux: add support for TechnoTrend CT2-4650 CI v2

---

packages/multimedia/ffmpeg/package.mk

Disabling ARMv6T is preventing some ARM ASM from being used (ie. cabac optimisations in HEVC code) as `HAVE_ARMV6T2_INLINE` is not enabled, which is hurting performance.
Unless there's a specific reason to disable ARMv5TE then might as well leave it available as well.

ffmpeg: Stop disabling ARMv5TE and ARMv6T2 - needed by ASM optimisations

---

packages/multimedia/ffmpeg/package.mk

I've had this patch in my builds for quite a while. Latest newclock5 RPi FFmpeg HEVC optimisations require these extra libraries, includes and defines. Should be safe to merge ahead of the very latest HEVC optimisations, which will eventually appear in in the rpb-backports patches.

[rbp] Add extra FFmpeg HEVC dependencies

---

packages/mediacenter/kodi/patches/kodi-100.14-move-pulse-device-to-end-of-list.patch

Thanks @fritsch for this.
This makes it so that pulseaudio output isn't selected automatically so we don't have people accidentally using it.
This fixes #4585 
keep open till @fritsch gives the go ahead

kodi: add patch so pulseaudio is at the end of the list

---

scripts/mkimage

fix issue like this
```
image: creating filesystem on part1...
losetup: /dev/loop0: device is busy
```

scripts/mkimage: sync disk few more times

---

packages/tools/installer/config/installer.conf

Missed this.
http://openelec.tv/forum/120-news-announcements/79858-release-openelec-6-0-1?start=15#156707

installer: Bump FAT partition size in line with disk image

---

packages/mediacenter/kodi/patches/kodi-995.20-black-screen-when-switching-channels-during-live-tv.patch

The patch alters Kodi AMLCodec.cpp to init handles to an invalid value. This fixes http://trac.kodi.tv/ticket/16515.
I also removed a previous workaround for this bug by Chris (koying, usleep) which is obsolete then and only worked on some systems.
(A later version of Kodi will probably have this fix included if my pull request to the Kodi sources will be accepted.)
/Zweikeks

bug fix for http://trac.kodi.tv #16515

---

packages/web/curl/package.mk
packages/x11/lib/pixman/package.mk

~~libcec should be safe.~~ nevermind, needs p8-platform
Curl update might need some more testing then what I was able to provide.
pixman should also be safe.
Will look for other updates to include as well.

Various package updates

---

packages/linux-drivers/tbs-linux-drivers/package.mk

- fix MMI not stable with CI slots on 6910 
- improve MAC address support for all boards currently in production 
- add support for TBS6290SE 
- improve TBS 6909 driver

tbs-linux-drivers: update to tbs-linux-drivers-160126

---

packages/devel/binutils/package.mk
packages/devel/dbus-glib/package.mk
packages/multimedia/imx-vpu/package.mk
packages/multimedia/libfslvpuwrap/package.mk
packages/python/devel/setuptools/package.mk
packages/sysutils/timezone-data/package.mk

dbus-glib and 	timezone-data should be backported to 6.0 branch

Package updates

---

packages/sysutils/dbus/package.mk

Updated to version 1.10.6 (CHANGELOG https://cgit.freedesktop.org/dbus/dbus/tree/NEWS?h=dbus-1.10)
Update package link, because http link don't work (linking to https site failed)

dbus: update version and package link

---

scripts/get

This avoids dropping `.lock` files all over the `sources` directory which is a bit messy - now uses the directory itself as the lock resource (read access).

build: Take a lock on the package download directory

---

config/addon/xbmc.python.module.xml

needed otherwise add-ons that use xbmc.python.module won't show up in the add-on manager
http://kodi.wiki/view/Addon.xml

config/addon/xbmc.python.module.xml: update to use xbmc.python.script

---

packages/audio/pulseaudio/patches/pulseaudio-0900.03-dont_relink_against_host.patch

Otherwise, libtool will try to link against the system libvorbis (originating from the the libsndfile.la) during installation where libpulse.so gets relinked.
Running `libtoolize` alone to replace the provided `ltmain.sh` by the already patched one from libtool does not work and running a complete `autoreconf`produces a broken `configure`.

pulseaudio: fix ltmain to not relink against host libs

---

packages/multimedia/libass/package.mk

- still leaks memory but at least up to date (OpenELEC/OpenELEC.tv/issues/4591)
- corrected site url

libass: update to libass-0.13.1

---

packages/linux-drivers/bcm_sta/patches/bcm_sta-0002-user_ioctl.patch
packages/linux-drivers/bcm_sta/patches/bcm_sta-0003-remove-date-time-macros.patch
packages/linux-drivers/bcm_sta/patches/bcm_sta-0004-null-pointer-crash.patch
packages/linux-drivers/bcm_sta/patches/bcm_sta-0005-rdtscl.patch

These are required for some driver bugs and changes in 4.3+ kernels. I've been using them with 32-bit builds for a while but have not build-tested them with a 64-bit build yet so please hold on merging until I confirm. Thanks.

bcm_sta: add patches for bugs and 4.3+ kernels

---

packages/devel/glibc/package.mk

I'd tested glibc 2.23 with RPi/RPi2 and no issues, but when building Generic it fails as follows:
```
/home/neil/projects/OpenELEC.tv/build.OpenELEC-Generic.x86_64-7.0-devel/toolchain/bin/x86_64-openelec-linux-gnu-gcc -B/home/neil/projects/OpenELEC.tv/build.OpenELEC-Generic.x86_64-7.0-devel/glibc-2.23/.x86_64-openelec-linux-gnu/ -march=x86-64 -m64   -shared -static-libgcc -Wl,-O1  -Wl,-z,defs -Wl,-dynamic-linker=/lib/ld-linux-x86-64.so.2  -B/home/neil/projects/OpenELEC.tv/build.OpenELEC-Generic.x86_64-7.0-devel/glibc-2.23/.x86_64-openelec-linux-gnu/csu/  -Wl,--version-script=/home/neil/projects/OpenELEC.tv/build.OpenELEC-Generic.x86_64-7.0-devel/glibc-2.23/.x86_64-openelec-linux-gnu/libresolv.map -Wl,-soname=libresolv.so.2 -Wl,-z,combreloc -Wl,-z,relro -Wl,--hash-style=both …
```

glibc: Fix Generic build issue after #4723

---

packages/sysutils/e2fsprogs/package.mk
packages/tools/mtools/package.mk
packages/tools/populatefs/package.mk
packages/tools/syslinux/package.mk
scripts/image
scripts/mkimage
tools/mkpkg/mkpkg_populatefs

Mtools is used to format and copy files to vfat partition.
Populatefs is used to copy files to ext4 partition.
Tested on imx6 with u-boot, Generic with BIOS and EFI boot.
To avoid messing around with ext4 partition we could also provide "empty" disk image file. Both partitions would be already formatted and storage partition would already contain resize file. Then mkimage script would only copy kernel, system, bootloader files and install bootloader.
But current approach is more flexible for future use.

scripts/mkimage: create disk image without sudo

---

packages/sysutils/e2fsprogs/package.mk

e2fsprogs: Don't parallel build

---

packages/devel/libcec/patches/libcec-03-amlogic-support.patch
projects/WeTek_Core/patches/linux/080-amlogic-cec-driver.patch
projects/WeTek_Play/patches/linux/080-amlogic-cec-driver.patch

Major rework. Nearly independent from the low level functions of the original driver. Unified for Meson 6 and Meson >=8.
To users outside the OpenELEC team:
If it doesn't work for you, check that you own a Wetek Play/Core. Currently nothing else supported.
I will close all issues that doesn't contain a link to the output of journalctl. 
If you don't know how to do that, don't create an issue. Your level of experiences would not allow me to work with you on it.

amlogic cec: major rework

---

projects/WeTek_Core/patches/linux/080-amlogic-cec-driver.patch
projects/WeTek_Play/patches/linux/080-amlogic-cec-driver.patch

Makes debug logging optional. Debug logging is on by default to catch early issues.
Can get later deactivated by:
`echo 0 >/sys/devices/virtual/amhdmitx/amhdmitx0/amlogic_cec_debug_config`
Default might be later off if the driver has proven its stability.

amlogic cec: make debug logging optional

---

packages/sysutils/eventlircd/udev.d/98-eventlircd.rules

This makes the power button actually power off the device.

eventlircd: add rule for WeTek_Core power button

---

packages/linux/patches/linux_010_disable_hid-sony_size_check.patch

Attempting to fix non-functioning of new-firmware Sony DualShock 4 controllers by backporting Jiri Kosina's patch to the current build of openelec (patch here https://git.kernel.org/cgit/linux/kernel/git/jikos/hid.git/commit/?h=for-4.5/sony&id=b71b5578a84d297954e4812ba0ca2d466e61cf42)
Frankly the change is so small I can't see it possibly breaking anything. This will be able to be tossed once we move to kernel 4.5 (because it'll be permanently integrated upstream).
This is tested and works on a current trunk build on a Minnowboard Max. It connects and sends input via bluetooth (although the keymap needs some effort, I haven't had time to resolve that issue yet)

Resolve issue with Sony DualShock 4 controllers by backporting linux 4.5 patch

---

packages/linux-drivers/wetekdvb/package.mk
packages/linux/package.mk

* Update Amlogic kernel to 3.10-ca65e57 (3.10.97)
* Update WeTek proprietary DVB binary driver to match the kernel

Update Amlogic kernel to 3.10-ca65e57 (3.10.97)

---

packages/lang/Python/package.mk

Python: fix cross compile to exclude host directories

---

packages/sysutils/amremote/package.mk

Fixes the #4759 issue for WeTek Play. PR #4769 fixed it for WeTek Core, but not for WeTek Play.
This PR finally fixes it for both devices.

Fix Power button not working on WeTek Play remote

---

packages/tools/mtools/package.mk

Add all mtools during host install step.
Especially mattrib which is used by syslinux.mtools during make image
When absent, this error is observed:
make image
> image: installing extlinux to part1...
> sh: mattrib: command not found
> syslinux.mtools: warning: failed to set system bit on ldlinux.sys
> sh: mattrib: command not found
> syslinux.mtools: warning: failed to set system bit on ldlinux.c32
> image: copying files to part1...

Add all mtools during host install step.

---

packages/devel/libcec/patches/libcec-03-amlogic-support.patch

The template for the Amlogic Libcec adapter, the exynos adapter, was not thread safe. Changed this for the Amlogic adapter now.
Thanks to @fritsch that pointed me to it.

libcec: make Amlogic adapter thread safe

---

projects/WeTek_Core/linux/linux.arm.conf
projects/WeTek_Core/options
projects/WeTek_Play/options

Recent change in Amlogic kernel (https://github.com/codesnake/linux/commit/df3f50edddfe8cd512470f98bd35d5a7624e435a) now allows to build all default additional drivers without errors. So include them all into WeTek projects.

Include all default additional drivers into WeTek Play and WeTek Core projects

---

projects/WeTek_Core/patches/linux/080-amlogic-cec-driver.patch
projects/WeTek_Play/patches/linux/080-amlogic-cec-driver.patch

amlogic_cec: partly rollback for LG TV compatibility, successful tested by codesnake on Wetek Play and tested by me on Wetek Core and Samsung TV

partly rollback for LG compatibility

---

config/arch.aarch64
packages/mediacenter/kodi/patches/kodi-999.10-aarch64-support.patch
packages/mediacenter/kodi/patches/kodi-999.11-fix-aarch64-compile.patch
packages/sysutils/fuse/patches/fuse-0001_aarch64-support.patch

This should get most of the relevant packages to build for aarch64 and will be helpful when to upstream this while I work on the Odroid C2
I have some other amlogic specific aarch64 patches in another branch.
@sraue take a look at the config/arch.arm64 file and see if you are ok with this.
Not sure if the `TARGET_CPU_FLAGS="+crc+crypto"` line is really needed but it did no harm for me while building.
https://gcc.gnu.org/onlinedocs/gcc/AArch64-Options.html
maybe @codesnake can have a look too.

add generic aarch64 support

---

packages/lang/gcc/patches/gcc-mark-armv8-vcvt-instructions-as-unconditional-69135.patch

When compiling for armv8, eg. `TARGET_SUBARCH=armv8-a+crc`, gcc 5.3.0 will incorrectly generate conditional instructions when compiling `alsa-lib` (specifically, `alisp`) and `libpulsecore`, eg.:
```
{standard input}: Assembler messages:
{standard input}:9597: Error: instruction cannot be conditional -- `vcvtmeq.s32.f64 s15,d16'
Makefile:375: recipe for target 'alisp.lo' failed
```
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=69135
https://gcc.gnu.org/ml/gcc-bugs/2016-01/msg00139.html

gcc: Mark ARMv8 vcvt instructions as unconditional

---

packages/linux-drivers/wetekdvb/package.mk
packages/linux/package.mk

* Update kernel to 3.10-0f60813 (3.10.98).
The updated kernel has 2 important fixes: https://github.com/codesnake/linux/commit/58ad7d59f5bc4a617e0ef5f001e5d90cccbe5e6e and https://github.com/codesnake/linux/commit/98d35a0d59fcfb4bacccc81dfabc84b78a3e97d4
* Update WeTek proprietary DVB module to 20160304.

Update Amlogic kernel to 3.10-0f60813 (3.10.98)

---

packages/databases/mysql/package.mk

Tested both with SSL and without, it works fine.
Kodi on windows and other distros have for some time now being able to use ssl with mysql but not OpenELEC.
Thanks!

Enable SSL for MySQL

---

config/functions
packages/tools/u-boot/release
scripts/image
scripts/mkimage
scripts/unpack

Allow the use of $HOME/.openelec for all packages, settings, etc.
This fixes issues with the linux package, and allows custom u-boot.

Various $HOME/.openelec (vendor) fixes

---

config/functions

Only noticed this problem after re-merging upstream into my base and attempting to build.  This should actually allow building said $PROJECT(s) in $HOME/.openelec/projects/$PROJECT as expected.

More $HOME/.openelec (Vendor) fixes

---

packages/linux/patches/4.4.4/linux-001-Intel-EDID-fix.patch

linux: patch to fix EDID parsing when ELD data spans multiple blocks

---

packages/audio/speex/package.mk
packages/multimedia/ffmpeg/package.mk

some streams use speex / opus audio codec and are silent without support enabled in ffmpeg

added speex / opus audio codec support

---

packages/linux-drivers/wetekdvb/package.mk
packages/linux/package.mk

* Update Amlogic kernel to 3.10-c8d5b2f (3.10.99). This update includes a fix of for WeTek Core screen capture (amvideocap).
* Update WeTek proprietary DVB module to fit the kernel.
closes #4827

Update Amlogic kernel to 3.10-c8d5b2f (3.10.99)

---

packages/sysutils/lcdproc/patches/lcdproc-FixBugNoritakeVFD.patch

Hello,
there is a bug in the driver NoritakeVFD.c, see patch. Columns and rows are swapped for setting the cursor position.
It took me a lot of time to find this error and get the display working.
Hope it helps others.
Tested with Noritake CU20045SCPB-T31A connected via serial line to RPi2 as well as desktop with Ubuntu.
Regards
P.S. The Noritake VFD displays are really nice to build a media player with "old school touch". For reasonable prices you can get it on the well known online market auction platform.

Fix bug in Noritake VFD driver

---

packages/sysutils/busybox/package.mk

busybox package allows configuration on a per project basis by referencing a config file in the project directory. For example, if a developer wanted to add wget to the available init stage commands provided by busybox they could do so in the projects/myproject/busybox/busybox-init.conf file. This feature exist today.
The change here allows the same override mechanics on the script named "init" which likely is the consumer of the new command. For example, by adding wget to the busybox command init configuration the init script can call wget and load a root file system from an http server.
Thank you for considering this change.

Allow project specific busybox init script

---

scripts/get

There is no point in using this option:
- either you want http
- or you want to use https, and you use it corretly

Remove the `--no-check-certificate` option from the build

---

scripts/checkdeps

This allows to build OpenELEC on OpenSUSE 42.1 and most probably earlier.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openelec/openelec.tv/4957)

scripts/checkdeps: add support for OpenSUSE

---

packages/tools/u-boot/package.mk
packages/tools/u-boot/patches/u-boot-004-add-support-for-gcc6.patch

Signed-off-by: Jérôme Benoit <jerome.benoit@piment-noir.org>

u-boot: properly add GCC 6.X support
