OpenELEC/OpenELEC.tv

- packages/multimedia/vdr-satip/package.mk
- a lot bug fixes
- added support for Digital Devices CI extension for VDR >=2.1.7
> vdr-satip: update to vdr-satip-1.0.1

- packages/audio/alsa-lib/patches/alsa-lib-usb-audio-spdif.patch
Fixes: https://github.com/OpenELEC/OpenELEC.tv/issues/3523
> alsa-lib: Fix PHIREE U2 and Soundblaster F-Xi XD

- packages/mediacenter/OpenELEC-settings/scripts/backup-restore
- packages/mediacenter/OpenELEC-settings/scripts/factory-reset
- packages/mediacenter/OpenELEC-settings/system.d/backup-restore.service
- packages/mediacenter/OpenELEC-settings/system.d/backup-restore.target
- packages/mediacenter/OpenELEC-settings/system.d/factory-reset.service
- packages/mediacenter/OpenELEC-settings/system.d/factory-reset.target
- packages/sysutils/busybox/scripts/fs-resize
- packages/sysutils/busybox/scripts/init
- packages/sysutils/busybox/system.d/fs-resize.service
- packages/sysutils/busybox/system.d/fs-resize.target
> fs-resize: move as systemd target

- packages/tools/u-boot/scripts/update.sh
- projects/imx6/bootloader/uEnv.txt
Default is 24 bit. 16 bit was set for performance reasons, but image quality is quite bad.
> IMX6: Don't override user set colors

- projects/imx6/bootloader/uEnv.txt
After discussion with @smallint and @wolfgar - this should be added as default.
> IMX: Disable console blank

- projects/WeTek_Play/patches/linux/140-fix_amvidocap_src_rect_typo.patch
- projects/WeTek_Play/patches/linux/150-add_led_to_devicetree.patch
> [WeTek_Play] - fix typo and restore powerled access

- projects/WeTek_Play/patches/linux/30-add_bootargs_to_device_tree.patch
lost after switch to wetek_play.dtd
//cc @codesnake
> wetek_play: set scaling_max_freq=1512000

- packages/lang/Python/package.mk
no need to include ossaudiodev module ?
> disable python ossaudiodev module

- packages/mediacenter/kodi/patches/kodi-999.95-backportPR6312PR6311PR6295.patch
Some backports. A good candidate for OE 5.0.2
Everything already is in kodi mainline.
> Kodi: Backport PR6312 PR6311 PR 6295

- packages/network/avahi/system.d/avahi-daemon.service
> avahi: start after network.target

- packages/web/curl/package.mk
> curl: Describe why we want it stable

- packages/sysutils/busybox/scripts/init
too much rpi whinners on forums. looks like most of our users give zero fuck about manualy repairing
quick and dirty. needs testing.
pls dont merge
> init: fsck -y when automatic repair fails

- packages/mediacenter/kodi/patches/kodi-053-add-custom-key-id.patch
fixes #3932 
I will send upstream to kodi as well
> Add home key id for Rii i7 remote

- projects/WeTek_Play/patches/linux/30-wifi_eth_leds_control.patch
Add a patch that activates the Ethernet and WiFi LEDs on the front panel.
> projects/WeTek_Play: Activate Ethernet and WiFi LEDs

- config/graphic
> Dove cleanup

- packages/multimedia/libva-intel-driver/patches/libva-intel-driver-01-fix-mcdi-on-ivb-byt-snb.patch
This needs testing.
Issue here: https://bugs.freedesktop.org/show_bug.cgi?id=79765
PR here: http://lists.freedesktop.org/archives/libva/2015-March/003243.html
> libva-intel-driver: Fix Advanced deinterlacing on IVB SNB BYT

- packages/multimedia/ffmpeg/package.mk
no need to export :)
https://www.diffchecker.com/1sr5tomg
did not try to compile for other than x86_64
> ffmpeg: move pkg-config to configure

- scripts/get
terminal output might be blank
> fixed: add missing quotes

- packages/multimedia/libva/package.mk
> libva: doesn't fail with subdir

- packages/sysutils/systemd/config/system.d/cifs.mount.sample
- packages/sysutils/systemd/config/system.d/nfs.mount.sample
Replaced the non-existing command "servicectl" by the correct "systemctl".
This was already done a couple lines above but strange enough not everywhere...
> systemctl instead of servicectl

- packages/compress/unzip/package.mk
- packages/sysutils/keyutils/patches/keyutils-02-cflags.patch
- packages/tools/plymouth-lite/package.mk
Issues detected with new project I'm working on which is using some different compiler flags.
Tested on all current projects.
> Fix compile flags

- packages/linux-drivers/mt7601u/package.mk
- projects/Generic/options
- projects/RPi/options
- projects/RPi2/options
- tools/mkpkg/mkpkg_mt7601u
This add support for the mt7601u chipset used in some wireless devices.
This is a rebase of #3494
> New Package - mt7601u

- packages/wayland/libinput/package.mk
- packages/x11/driver/xf86-input-libinput/package.mk
> Update libinput and xf86-input-libinput

- packages/linux-drivers/wetekdvb/package.mk
- packages/linux/package.mk
* Update kernel to 3.10.76
* Update WeTek DVB binary driver
> Wetek kernel update

- packages/wayland/libinput/package.mk
> [libinput] update to 0.15.0

- projects/imx6/patches/kodi/kodi-19-PR6898.patch
- projects/imx6/patches/kodi/kodi-20-PR-6878.patch
- projects/imx6/patches/kodi/kodi-21-increase-render-buffers.patch
- projects/imx6/patches/kodi/kodi-22-only-workaround-main-30.patch
- projects/imx6/patches/kodi/kodi-23-string-utils.patch
- projects/imx6/patches/kodi/kodi-24-workaround-crop.patch
- projects/imx6/patches/kodi/kodi-25-1920.patch
- projects/imx6/patches/kodi/kodi-25-fix-guilayer-patches.patch
- projects/imx6/patches/kodi/kodi-26-check-all-resolutions.patch
Whole lot of stuff ... Make IMX halfway working again. 3D SBS still broken, rest is fixes only.
> IMX: Code sync

- packages/devel/libcec/package.mk
- packages/devel/libcec/patches/libcec-00-imx6-support.patch
- packages/mediacenter/kodi-theme-Confluence/package.mk
- packages/mediacenter/kodi/package.mk
- packages/mediacenter/platform/package.mk
- packages/mediacenter/platform/patches/platform-01-revert-cc-badness.patch
- packages/mediacenter/platform/patches/platform-02-add-PR6.patch
> bump libcec & kodi

- projects/imx6/patches/linux/linux-250-fix-dvbsky.patch
Add patch to fix dvbsky driver, fixes #4140
> projects/imx6/patches/linux: fix dvbsky driver

- packages/mediacenter/kodi-binary-addons/audiodecoder.qsf/package.mk
sorry for the quick bump but i found a bug that rendered the add-on unusable..
> bump audiodecoder.qsf

- packages/graphics/soil/package.mk
- packages/mediacenter/kodi-binary-addons/screensaver.asteroids/package.mk
- packages/mediacenter/kodi-binary-addons/screensaver.biogenesis/package.mk
- packages/mediacenter/kodi-binary-addons/screensaver.greynetic/package.mk
- packages/mediacenter/kodi-binary-addons/screensaver.matrixtrails/package.mk
- packages/mediacenter/kodi-binary-addons/screensaver.pingpong/package.mk
- packages/mediacenter/kodi-binary-addons/screensaver.pyro/package.mk
- packages/mediacenter/kodi-binary-addons/screensaver.stars/package.mk
- tools/mkpkg/mkpkg_screensaver.asteroids
- tools/mkpkg/mkpkg_screensaver.biogenesis
- tools/mkpkg/mkpkg_screensaver.greynetic
- tools/mkpkg/mkpkg_screensaver.matrixtrails
- tools/mkpkg/mkpkg_screensaver.pingpong
- tools/mkpkg/mkpkg_screensaver.pyro
- tools/mkpkg/mkpkg_screensaver.stars
This adds some screensaver addons.
> Add screensavers

- packages/graphics/glfw/package.mk
- packages/graphics/ilmbase/package.mk
- packages/graphics/openexr/package.mk
- packages/graphics/vsxu/package.mk
- packages/graphics/vsxu/patches/vsxu-01-fix-order.patch
- packages/graphics/vsxu/patches/vsxu-02-fix-glfw.patch
- packages/graphics/vsxu/patches/vsxu-03-fix-exr.patch
- packages/graphics/vsxu/patches/vsxu-04-fix-freetype.patch
- packages/mediacenter/kodi-binary-addons/visualization.vsxu/package.mk
- tools/mkpkg/mkpkg_visualization.vsxu
adds a vsxu based addon. had to climb a dependency tree..
> Add visualization.vsxu

- projects/imx6/filesystem/usr/lib/systemd/system/imx6-poweroff.service
This turns off the LED and the display after all other shutdown stuff is done.
> IMX: Power off LED and display after poweroff

- distributions/OpenELEC/options
Minor typo, but user friendly is two words.
> Fix typo on DESCRIPTION

- distributions/OpenELEC/options
According to dict.cc, "user-friendly" is more common. See http://www.dict.cc/?s=user-friendly
;-)
> Fix typo "user-friendly" properly

- projects/imx6/filesystem/usr/share/alsa/cards/imx-sgtl5000.conf
needed by TBS matrix and probably Solidrun's HummingBoard-i2eX
> project imx6: add sgtl5000 analog output alsa config file

- packages/x11/driver/xf86-video-nvidia/package.mk
> xf86-video-nvidia: update to xf86-video-nvidia-352.21

- config/noobs/partition_setup.sh
Add a required whitespace before `]` in conditional.
> Syntax error in shell conditional

- packages/mediacenter/kodi/patches/kodi-100.99-keyboardlayouts-add-some-symbol-keys-to-english-qwer.patch
as title says. adding . : / @ keys to english virtual keyboard.
I wont send this upstream because meh bikesheding.
let me know if this is acceptable here or not.
> kodi: enhance english kb layout a bit.

- packages/mediacenter/kodi-binary-addons/screensavers.rsxs/package.mk
- packages/mediacenter/kodi/patches/kodi-995.01-addonpath.patch
- scripts/create_addon
- tools/mkpkg/mkpkg_screensavers.rsxs
@sraue can we get the kodi patch into next beta/rc ?
EDIT: forgot to mention. it is already sent upstream as part of https://github.com/xbmc/xbmc/pull/5329
> re-add screensavers.rsxs

- packages/tools/installer/scripts/installer
'ssh' in syslinux.conf is not a good idea (anymore). must go.
backups.. this needs ack from @vpeter4 but "bug reports" like #4232 are meh if you ask me.
> installer clean up

- packages/linux/patches/4.1.4/linux-063-xpad-fix_xbox360_wireless.patch
> linux/patches/xpad-fix: update patch for kernel v4.1.4

- projects/WeTek_Play/patches/linux/203-wetek-dvb-less-log-spam.patch
@codesnake FYI
~~I got new wetekdvb.ko from Sasa and repackaged it.~~
> wetek/dvb: reduce debug log spam

- projects/imx6/options
- projects/imx6/patches/linux/linux-331-udoo-device_tree.patch
- projects/imx6/patches/linux/linux-335-udoo-vt1613-audio-driver.patch
Next PR based on this one will cover SPL based bootloader.
> projects/imx6/patches/linux: add udoo dual device tree

- packages/network/openssh/system.d/sshd.service
> sshd: restart on failure. dont wait for network

- scripts/get
because joe the builder. thats why.
and, it's a real bug. too :)
> scripts/get: 900s is too much

- packages/multimedia/libhdhomerun/package.mk
Expand discovery API to return DeviceAuth and BaseURL.
> libhdhomerun: update to libhdhomerun_20150826

- packages/tools/installer/scripts/installer
- projects/Generic/linux/linux.x86_64.conf
ref http://openelec.tv/forum/64-installation/78345-openelec-installation-no-devices-available
needs testing.
> add nvme block device support to kernel/installer

- packages/tools/installer/scripts/installer
fitst commit removes confusing and incorect statement about new hdds
safe for master/6.0
> installer cleanup

- packages/mediacenter/kodi-binary-addons/audioencoder.flac/package.mk
- packages/mediacenter/kodi-binary-addons/pvr.argustv/package.mk
- packages/mediacenter/kodi-binary-addons/pvr.filmon/package.mk
- packages/mediacenter/kodi-binary-addons/pvr.hts/package.mk
- packages/mediacenter/kodi-binary-addons/pvr.mythtv/package.mk
- packages/mediacenter/kodi-binary-addons/pvr.pctv/package.mk
- packages/mediacenter/kodi-binary-addons/pvr.stalker/package.mk
- packages/mediacenter/kodi-binary-addons/pvr.vbox/package.mk
- packages/mediacenter/kodi-platform/package.mk
kodi-platform change is due to #4353
> binary-addons: sync for isengard

- packages/linux-drivers/wetekdvb/package.mk
- packages/linux/package.mk
* Update Amlogic kernel to 3.10-9df7905 (3.10.90)
* Update WeTek proprietary DVB module to 20151007
> Update Amlogic kernel and WeTek proprietary DVB module

- packages/mediacenter/kodi-theme-Confluence/package.mk
- packages/mediacenter/kodi/package.mk
> [kodi] update to 15.2 final

- packages/mediacenter/kodi/package.mk
> kodi: remove xrandr support

- packages/mediacenter/kodi/patches/kodi-999.60-udevprovider-fix-mounting-raw-filesystems.patch
@stefansaraev anything else you can think of?
> kodi: add backported patch for xbmc/xbmc#8334

- packages/sysutils/dbus/package.mk
@MilhouseVH can you include this in your builds?
> dbus: update to version 1.10.4

- packages/multimedia/ffmpeg/package.mk
this may be required for kodi 17
EDIT: so enable it sooner than later.
> ffmpeg: enable mjpeg encoder

- packages/multimedia/libaacs/patches/libaacs-0001-correct-debug-log-in-_find_config_entry.patch
- packages/multimedia/libaacs/patches/libaacs-0002-always-write-logentry-in-case-of-corrupted-disc.patch
- packages/multimedia/libaacs/patches/libaacs-0003-mkb-fix-endless-loop-in-_record.patch
This fixes #4378 
patches are from, http://git.videolan.org/?p=libaacs.git;a=search;s=Roland+Fischer;st=author
> libaacs: add upstream patches

- packages/linux-drivers/wetekdvb/package.mk
- packages/linux/package.mk
- projects/WeTek_Play/linux/linux.arm.conf
* Update Amlogic kernel to 3.10-0b9823d (3.10.94)
* Update WeTek proprietary DVB driver to match the kernel
> Update Amlogic kernel and WeTek DVB driver

- packages/graphics/bcm2835-driver/package.mk
- packages/graphics/mesa/package.mk
- packages/multimedia/libaacs/patches/libaacs-0001-correct-debug-log-in-_find_config_entry.patch
- packages/multimedia/libaacs/patches/libaacs-0002-always-write-logentry-in-case-of-corrupted-disc.patch
- packages/multimedia/libaacs/patches/libaacs-0003-mkb-fix-endless-loop-in-_record.patch
- packages/network/libshairplay/package.mk
- packages/tools/bcm2835-bootloader/package.mk
I'll include various backported commits here.
Let me know if I missed anything.
> openelec-6.0 backports

- packages/addons/repository/repository.unofficial.addon.pro/package.mk
cosmetic change - unless pkg_rev increments the new addon description text isn't picked up
> addons: bump unofficial repo pkg_rev

- distributions/OpenELEC/options
cleaner looking banner for the SSH console
> options: banner cosmetics

- scripts/mkimage
backporting the 7.0 change for 6.0.1 builds - the sooner we push this to users the better..
> image: increase img to 512MB for 6.0.1

- distributions/OpenELEC/options
- scripts/image
> Fix ssh banner whitespace

- packages/addons/service/multimedia/vdr-addon/changelog.txt
- packages/addons/service/multimedia/vdr-addon/package.mk
- packages/multimedia/vdr-plugin-vnsiserver/package.mk
- packages/multimedia/vdr-satip/package.mk
update to latest rls of sat>ip and vnsi-server
not yet compile/runtime tested
> vdr-addon bump 6.0.2

- packages/linux-drivers/tbs-linux-drivers/package.mk
> tbs-linux-drivers: update to tbs-linux-drivers-151229

- packages/network/connman/patches/connman-06-fix-lease-expiry-issues.patch
As mentioned by @stefansaraev: https://github.com/OpenELEC/OpenELEC.tv/pull/4594#issuecomment-177287153
> connman: fix lease expiry issues

- packages/debug/gdb/package.mk
- packages/web/curl/package.mk
I think we want all of these.
@stefansaraev do we want the stripping changes too? 
ie:
stefansaraev/TB@8677d037bb9c1af54f6ff6e861c4b669c32cd26a
stefansaraev/TB@1b40e92ba23866985588d50f8c4e3cb162611d9b
stefansaraev/TB@cc2906b7472c4bd7e69796b046821c0b56c24956
etc.
I'm asking because I'm not sure why you chose to add a new function `strip_debug` to some packages. :)
> various build fixes

- tools/mkpkg/mkpkg_binary-addons
So we can package exactly what kodi requires.
> mkpkg_binary-addons: update to include platform

- packages/linux/patches/4.1.16/linux-226-avermedia-volar-hd2.patch
> linux: add support for AVerTV Volar HD 2

- packages/addons/service/multimedia/vdr-addon/changelog.txt
- packages/addons/service/multimedia/vdr-addon/package.mk
- packages/multimedia/vdr-plugin-restfulapi/package.mk
- packages/multimedia/vdr-plugin-vnsiserver/package.mk
- packages/multimedia/vdr-satip/patches/vdr-satip-02-upstream.patch
> vdr-addon bump 7.0.2

- packages/graphics/ftgl/patches/ftgl-01-cmake.patch
- packages/mediacenter/kodi-binary-addons/visualization.projectm/patches/visualization.projectm-01-Revert-changed-get-rid-of-DATAPATH-definition.patch
Fixup some patches so @chewitt can sleep at night
> ftgl and visualizations.projectm

- config/addon/xbmc.python.module.xml
> backport of #4695 

- config/noobs/partitions.json
> backport of #4699 

- config/noobs/partitions.json
> config/noobs: use 512MB parition size for consistency

- packages/graphics/mesa/package.mk
- packages/x11/xserver/xorg-server/package.mk
Both bugfix releases
release notes aren't live yet [link](https://cgit.freedesktop.org/mesa/mesa/commit/?h=11.1&id=7bcd827806b0816d61122ba3d37dd40178d96d98)
http://www.mesa3d.org/relnotes/11.1.2.html
https://lists.freedesktop.org/archives/xorg-announce/2016-February/002674.html
> Package updates

- packages/devel/libcec/patches/libcec-03-amlogic-support.patch
- projects/WeTek_Core/patches/linux/080-amlogic-cec-driver.patch
- projects/WeTek_Play/patches/linux/080-amlogic-cec-driver.patch
Reverts OpenELEC/OpenELEC.tv#4737
> Revert "major rework"

- packages/linux/patches/4.4.2/linux-224_Hauppauge_WinTV-soloHD.patch
Signed-off-by: Stephan Raue <stephan@openelec.tv>
> linux: add support for Hauppauge WinTV-soloHD

- tools/mkpkg/mkpkg_kodi
- saves a lot bandwith + faster
> mkpkg_kodi: git clone without history

- packages/mediacenter/kodi/scripts/systemd-addon-wrapper
> kodi: adjust systemd-addon-wrapper for systemd-229

- projects/WeTek_Core/patches/linux/080-amlogic-cec-driver.patch
- projects/WeTek_Play/patches/linux/080-amlogic-cec-driver.patch
Much more reliable start, specially on the play.
> removed what I don't understand and lowered delay

- packages/linux-firmware/wlan-firmware/package.mk
Do not merge until wlan-firmware is tagged!
> wlan-firmware: update to wlan-firmware-0.0.31

- packages/linux-firmware/wlan-firmware/package.mk
Do not merge until wlan-firmware is tagged!
> wlan-firmware: update to wlan-firmware-0.0.31 (backport)

- projects/WeTek_Core/patches/linux/080-amlogic-cec-driver.patch
- projects/WeTek_Play/patches/linux/080-amlogic-cec-driver.patch
amlogic_cec: bug fixes and clean ups
> amlogic_cec: bug fixes and clean ups

- config/arch.arm
- config/arch.x86_64
- config/path
- packages/linux-drivers/RTL8188EU/package.mk
- packages/linux-drivers/RTL8192CU/package.mk
- packages/linux-drivers/RTL8192DU/package.mk
- packages/linux-drivers/RTL8192EU/package.mk
- packages/linux-drivers/RTL8812AU/package.mk
- packages/linux-drivers/bcm_sta/package.mk
- packages/linux/package.mk
- scripts/image
This is needed so that #4787 can be properly implemented
Thanks @stefansaraev
> buildsys: define TARGET_KERNEL_ARCH early

- packages/linux/package.mk
some fixups as aarchr64 requires building "Image"
> linux: aarch64 fixup

- packages/linux/package.mk
- projects/Generic/options
- projects/RPi/options
- projects/RPi2/options
- projects/WeTek_Core/options
- projects/WeTek_Play/options
- projects/imx6/options
- scripts/image
Thanks again @stefansaraev 
This simplifies things as we simply use KERNEL_TARGET for each project.
> linux: use KERNEL_TARGET as make target

- packages/linux/patches/4.4.3/linux-063-xpad-fix_xbox360_wireless.patch
> xpad: update Xbox 360 wireless controller driver w/latest fixes

- projects/WeTek_Core/patches/linux/080-amlogic-cec-driver.patch
- projects/WeTek_Play/patches/linux/080-amlogic-cec-driver.patch
- code of delayed init now part of open call
- interrupt handling moved into open/release
- removed some debug lines
> redesigned initialization

- packages/tools/installer/scripts/installer
> installer: add notification dialog upon completion of install

- packages/devel/libcec/patches/libcec-03-amlogic-support.patch
This fixes hanging on shutdown
> backported amlogic cec fix from master

- projects/WeTek_Core/patches/linux/080-amlogic-cec-driver.patch
- projects/WeTek_Play/patches/linux/080-amlogic-cec-driver.patch
This has to be used in OpenELEC-7.0 too
> messages was stuck in the read queue

- packages/security/libressl/config/libcrypto.pc
- packages/security/libressl/config/libssl.pc
- packages/security/libressl/config/libtls.pc
- packages/security/libressl/config/openssl.pc
Signed-off-by: Jérôme Benoit <jerome.benoit@piment-noir.org>
> LibreSSL: sync pkg-config configuration version with package version

- scripts/checkdeps
Building under linuxmint failed due to missing entry
> adding linuxmint distro

- packages/lang/gcc/package.mk
Signed-off-by: Mathieu Malaterre <malat@debian.org>
> gcc: add libatomic option

- packages/sysutils/libevdev/package.mk
- packages/x11/lib/libxcb/package.mk
- packages/x11/xserver/xorg-server/package.mk
This is a cosmetic pull request which remove extra `doxygen` steps.
> ci20 doxygen

- packages/graphics/libjpeg-turbo/patches/libjpeg-turbo-mips.patch
Signed-off-by: Mathieu Malaterre <malat@debian.org>
> libjpeg-turbo: fix compilation on mipsel
